name: Clash rules
on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
        shell: bash
  
      - name: Generate folder and files
        run: |
          
          declare -A source=(
            ["freenode"]="https://raw.githubusercontent.com/ripaojiedian/freenode/main/clash"
            ["oaxynode"]="https://cdn.jsdelivr.net/gh/zyzmzyz/free-nodes@master/Clash.yml"
            ["obxynode"]="https://raw.githubusercontent.com/oslook/clash-freenode/main/clash.yaml"
            ["ocxynode"]="https://raw.githubusercontent.com/aiboboxx/clashfree/main/clash.yml"
            ["odxynode"]="https://raw.githubusercontent.com/anaer/Sub/main/clash.yaml"
            ["oexynode"]="https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml"
          )
          
          for key in ${!source[@]};do
            curl ${source[$key]} > $key.yaml
            sed -i '/^proxies:/,/^proxy-groups:/!d' $key.yaml
            sed -i '$d' $key.yaml
          done
          
      - name: Git push to release
        run: |
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f origin release
