name: Clash rules
on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
        shell: bash

      - name: Download python3 file and run
        run: | 
          curl https://raw.fastgit.org/Lazyhms/clash-rules/free/v2ray.py > v2ray.py
          
          python3 v2ray.py
          
          if [ -s v2ray.py ]; then rm -f v2ray.py; fi
          
      - name: Generate folder and files
        run: |
          
          declare -A source=(
            ["freenode"]="https://raw.githubusercontent.com/oslook/clash-freenode/main/clash.yaml"
            ["oaxynode"]="https://raw.githubusercontent.com/anaer/Sub/main/clash.yml"
            ["obxynode"]="https://raw.githubusercontent.com/alanbobs999/TopFreeProxies/master/Eternity.yml"
            ["ocxynode"]="https://raw.githubusercontent.com/aiboboxx/clashfree/main/clash.yml"
            # ["greenfish"]="https://raw.gitfast.tk/GreenFishStudio/GreenFish/master/Subscription/Clash/GreenFishYYDS"
          )
          
          for key in ${!source[@]};do
            curl ${source[$key]} > $key.yaml
            sed -i '/^proxies:/,/^proxy-groups:/!d' $key.yaml
            sed -i '$d' $key.yaml
          done
          
      - name: Git push to release
        run: |
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f origin release
