name: Clash rules
on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
        shell: bash

      - name: Generate folder and files
        run: |
        
          curl "https://cdn.jsdelivr.net/gh/oslook/clash-freenode@master/clash.yaml" > freenode.yaml
          curl "https://raw.gitfast.tk/GreenFishStudio/GreenFish/master/Subscription/Clash/GreenFishYYDS" > greenfish.yaml
          curl "https://raw.githubusercontent.com/anaer/Sub/main/clash.yml" > oaxynode.yaml
          curl "https://raw.githubusercontent.com/alanbobs999/TopFreeProxies/master/Eternity.yml" > obxynode.yaml
          curl "https://raw.fastgit.org/Rokate/Proxy-Sub/main/clash/clash_ssr.yml" > ocxynode.yaml

          sed -i '/^proxies:/,/^proxy-groups:/!d' freenode.yaml
          sed -i '/^proxies:/,/^proxy-groups:/!d' greenfish.yaml
          sed -i '/^proxies:/,/^proxy-groups:/!d' oaxynode.yaml
          sed -i '/^proxies:/,/^proxy-groups:/!d' obxynode.yaml
          sed -i '/^proxies:/,/^proxy-groups:/!d' ocxynode.yaml

          sed -i '$d' freenode.yaml
          sed -i '$d' greenfish.yaml
          sed -i '$d' oaxynode.yaml
          sed -i '$d' obxynode.yaml
          sed -i '$d' ocxynode.yaml

          if [ ! -s freenode.yaml ]; then rm -f freenode.yaml; fi
          if [ ! -s greenfish.yaml ]; then rm -f greenfish.yaml; fi
          if [ ! -s oaxynode.yaml ]; then rm -f oaxynode.yaml; fi
          if [ ! -s obxynode.yaml ]; then rm -f obxynode.yaml; fi
          if [ ! -s ocxynode.yaml ]; then rm -f ocxynode.yaml; fi

      - name: Git push to release
        run: |
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f origin release
