name: Clash rules
on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
        shell: bash

      - name: Generate folder and files
        run: |
        
          curl "https://cdn.jsdelivr.net/gh/oslook/clash-freenode@master/clash.yaml" > freenode.yaml
          curl "https://drive.google.com/uc?export=download&id=1u9bolaXHzUQa4mAcmWaasM5-J-Zx4flY" > freefq.yaml
          curl "https://raw.githubusercontent.com/changfengoss/pub/main/data/2021_11_01/YKtuZG.yaml" > yktuzg.yaml
          
          sed -i '/^proxies:/,/^proxy-groups:/!d' freenode.yaml 
          sed -i '/^proxies:/,/^proxy-groups:/!d' freefq.yaml 
          sed -i '/^proxies:/,/^proxy-groups:/!d' yktuzg.yaml 
          
          sed -i '$d' freenode.yaml
          sed -i '$d' freefq.yaml
          sed -i '$d' yktuzg.yaml
          
          if [ ! -s freenode.yaml ]; then rm -f freenode.yaml; fi
          if [ ! -s freefq.yaml ]; then rm -f freefq.yaml; fi
          if [ ! -s yktuzg.yaml ]; then rm -f yktuzg.yaml; fi
          
      - name: Git push to release
        run: |
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f origin release
          
      - name: Purge jsdelivr cdn
        run: |
          for file in $(ls); do
            curl "https://purge.jsdelivr.net/gh/${{ github.repository }}@release/${file}"
          done
