name: Clash rules
on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
        shell: bash

      - name: Generate folder and files
        run: |
        
          curl "https://cdn.jsdelivr.net/gh/oslook/clash-freenode@master/clash.yaml" > freenode.yaml

          sed -i '/^proxies:/,/^proxy-groups:/!d' freenode.yaml 
          
          sed -i '$d' freenode.yaml
          
          if [ ! -s freenode.yaml ]; then rm -f freenode.yaml; fi
          
          curl "https://dllx.tk/GreenFishYYDS-Clash" > greenfish.yaml

          sed -i '/^proxies:/,/^proxy-groups:/!d' greenfish.yaml 
          
          sed -i '$d' greenfish.yaml
          
          if [ ! -s greenfish.yaml ]; then rm -f greenfish.yaml; fi
          
      - name: Git push to release
        run: |
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f origin release
          
      - name: Purge jsdelivr cdn
        run: |
          for file in $(ls); do
            curl "https://purge.jsdelivr.net/gh/${{ github.repository }}@release/${file}"
          done
